require 'axlsx'
require 'securerandom'
require 'colorize'
require 'nokogiri'
require 'open-uri'
require 'pry'

require_relative './rescrape/version'
require_relative './rescrape/controllers/controller'
require_relative './rescrape/excel'
require_relative './rescrape/models/job'
require_relative './rescrape/models/search'
require_relative './rescrape/scrapers/scrape'
require_relative './rescrape/scrapers/scrape_indeed'
require_relative './rescrape/scrapers/scrape_dice'
require_relative './rescrape/scrapers/scrape_career_builder'
require_relative './rescrape/scrapers/scrape_cyber_coders'
